spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Ex11CrudTest
    username: root
    password: linda010495-pw

  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop

---
environment: test

spring:
  datasource:
    url: jdbc:h2:mem:testDb
    username: test
    password: test
    driver-class-name: org.h2.Driver

  jpa:
    database: h2

